seminar2.
frogitcher/oop_misis_works_2022 pull request #10
Opened 2022-10-15 09:46 UTC by RomBurunduk

2022-10-15 09:47 UTC, frogitcher requested changes
не все задания готовы

2022-12-11 21:44 UTC, frogitcher requested changes
задачи на ч. методы решены не теми способами

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +    return ((pow ( x - x1, 2 ) + pow ( y - y1, 2 ) - pow(r,2)) > 0);
Может быть красивее лучше будет здесь пробежать по всем окружностям? (Т.е. сохранить их куда-то)
Еще конечно, хочется понятнее названия аргументов.
Название функции тоже хочется понятнее: IsInsideCircle, например

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +    double it=10000, acs=0;
лучше по разным строкам

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +    double data[n][3];
не, лучше вектор. Если совсем не хочется, то можно std::array. С-массивов в проде не видел

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +        cin >> data[i][j];
в проде все циклы и ифы обрамляют { }, даже если внутри одна строчка

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +            flag=1;
а вот был бы вектор или std::array, можно было бы здесь применить any_of

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +        }
поехало форматирование

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +    if (flag) acs+=1;
в одну строку тоже не разрешают, совсем

2022-12-11 21:44 UTC, frogitcher commented on number methods/jins/main.cpp
> +    if (flag) acs+=1;
если хочется в одну строку всё равно, можно acs += flag

2022-12-11 21:44 UTC, frogitcher commented on number methods/ananas/main.cpp
> +        std::cout<<std::fixed<<round(((integral(j,a,b)-integral(j-wid,a,b))*PI)*1000000)/1000000<<std::endl;
умножение и деление тоже не очень понимаю.. мутная формула

2022-12-11 21:44 UTC, frogitcher commented on number methods/polar point/main.cpp
> +    c=atan2(b,a);
Нет. Это нельзя. Было сказано.

2022-12-11 21:44 UTC, frogitcher commented on number methods/polar point/main.cpp
> +    c=atan2(b,a);
Задача была дана ровно с той целью, чтобы разложить что-нибудь в ряд

2022-12-16 16:30 UTC, closed without merging

2022-12-16 16:39 UTC, RomBurunduk commented on number methods/ananas/main.cpp
> +    return (b*b*x - (b*b*x*x*x)/(3*a*a));
> Просто интеграл. Так не интересно, не принимаю. Изучали численное интегрирование, его тут нет.
> Можно сказать: "но задачу же можно так решить, почему тогда?"
> Можно ответить, что если бы задача была другая, то это не прокатило бы. А эта задача уже хорошо достаточно хорошо подходит для тренировки

Изменил способ вычисления