AfanasevMA > Lab #1 & Contest #1
frogitcher/oop_misis_works_2022 pull request #23
Opened 2022-11-01 20:07 UTC by mrapplexz

2022-11-29 19:02 UTC, frogitcher approved these changes

2022-11-29 19:02 UTC, frogitcher commented on AfanasevMA/lab1/rational.h
> +//
Эти префиксы всё-таки хорошо бы удалть

2022-12-07 21:44 UTC, mrapplexz commented on AfanasevMA/contest1/e.cpp
> +        if (line.length() == 3 && std::tolower(line[0]) == 'y' && std::tolower(line[1]) == 'e' && std::tolower(line[2]) == 's') {
В STL же нет метода, который всю строку в lowercase конвертирует

2022-12-07 21:52 UTC, mrapplexz commented on AfanasevMA/contest1/a.cpp
> +    long int nums[n];
array<int, n> же не заработает, потому что нужно в compile time'е знать n
в вектор - да согласен

2022-12-11 22:15 UTC, frogitcher commented on AfanasevMA/contest1/e.cpp
> +        if (line.length() == 3 && std::tolower(line[0]) == 'y' && std::tolower(line[1]) == 'e' && std::tolower(line[2]) == 's') {
можно через std::transform

2022-12-11 22:15 UTC, frogitcher commented on AfanasevMA/contest1/e.cpp
> +        if (line.length() == 3 && std::tolower(line[0]) == 'y' && std::tolower(line[1]) == 'e' && std::tolower(line[2]) == 's') {
как лямбду передать собственно tolower

2022-12-11 23:42 UTC, frogitcher requested changes
нужно разложение в ряд и Симпсон

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest1/b.cpp
> +    std::set<long int> visited;
здесь можно было сортировку подсчетом сделать, т.е. не использовать сет

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest1/c.cpp
> +        }
опционально можно было out += (a + b + c + d > sum), но не знаю, было бы ли это лучше

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest1/d.cpp
> +        double spills = double(start) * a / double(sum);
можно только double(start), т.е. double(sum) не делать, т.к.:
это было бы эквивалентно (double(start) * a) / sum.
пусть x = double(start) * a. умножение имеет аргументы (double, int). int приводится к double, потом проводим умножение и получаем double.
после этого проводим x / sum. Деление тоже имеет аргументы (double, int). int тут ТОЖЕ приводится к double и только потом происходит деление. Поэтому целочисленного деления не будет. Ну и вот, не надо бояться целочисленного деления, если один из аргументов - double/float

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest1/g.cpp
> +    for (unsigned char i = 'a'; i <= 'z'; i++) {
просто char, т.к. он уже и так под капотом uint_8t

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest2/a.cpp
> +    }
Т.е. k = min(k, n-1)

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest2/b.cpp
> +                    throw std::invalid_argument("wtf");
может быть здесь было бы красивее через if () { } else if () { } ..., но это не точно

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest2/b.cpp
> +        process_batch();
функции лучше называть так: ProcessBatch

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest2/c.cpp
> +}
очень приятно выглядит

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest3/a.cpp
> +#define PI std::acos(-1)
лучше const double pi = std::acos(-1.0);
дефайны для подобных вещей использовать вот прямо совсем нельзя

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest3/a.cpp
> +    double o = std::atan2(y, x);
нет. нужно было разложить в ряд.

2022-12-11 23:42 UTC, frogitcher commented on AfanasevMA/contest3/c.cpp
> +    }
нет. надо было через Симпсона. это была задача на это.

2023-01-07 20:00 UTC, frogitcher approved these changes

2023-01-07 20:00 UTC, frogitcher commented on AfanasevMA/contest3/c.cpp
> +    // интересно, зачем гомер симпсон придумал интеграл?
чтобы считать численно на компе, а не на бумажке на 3 страницы расписывать:)

2023-01-07 20:00 UTC, merged