Class rational by pochuev
frogitcher/oop_misis_works_2022 pull request #27
Opened 2022-11-29 18:58 UTC by FRidere

2022-12-12 00:12 UTC, frogitcher requested changes
задачи на численные методы нужно переписать
задача про полярный угол - на разложение в ряд
задача про ананас - на численное интегрирование Симпсоном оп маленьким частям

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest2/contest24.cpp
> +            if(queue.size() != 0) {//std::cout << "here";
стоит подчистить комменты

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest2/contest24.cpp
> +                while (queue.size() != 0 and *(--(queue.end())) == reqElem) {
--(queue.end()) можно заменить на что-то покрасивше.
как минимум 2 способа:
1. queue.rbegin()
2. prev(queue.end())

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest2/contest24.cpp
> +                while (queue.size() != 0 and *(--(queue.end())) == reqElem) {
кстати не стоит называть переменную queue, т.к. есть такой тип

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest2/contest25.cpp
> +            if(value > c)
тут тоже хочется { }

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest2/contest25.cpp
> +            if(value > c)
весь иф можно заменить на ans += min(c, value) кстати

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest2/contest26.cpp
> +    return -1;
а, понял. найти k-е вхождение числа.
можно через find_if
например, как здесь
https://stackoverflow.com/questions/17865488/find-the-nth-element-satisfying-a-condition

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest2/contest27.cpp
> +            else if(paths[r].first > paths[l].first or paths[r].second > paths[l].first)
and, or, ... не пишут. пишут, все-таки, &&, ||, ...

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest3/first.cpp
> +    std::ifstream in("angle1.in",std::ios::binary | std::ios :: in);
а зачем нужны std::ios::binary | std::ios :: in ?

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest3/first.cpp
> +    ans = std::atan2(y,x);
нет. нужно разложить в ряд. задача была для этого

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest3/second.cpp
> +}
сеткой, ну ладно

2022-12-12 00:12 UTC, frogitcher commented on Pochuev/contest3/third.cpp
> +}
нет. задача была для того, чтобы сделать численное интегрирование. не для того, чтобы написать одну формулу и заслать

2022-12-18 20:20 UTC, FRidere commented on Pochuev/contest3/first.cpp
> +    std::ifstream in("angle1.in",std::ios::binary | std::ios :: in);
Это флаги открытия потока, написал их по старой привычке (так было в книжке по плюсам 98го стандарта, по которой я когда-то учился программировать), но они особо не нужны

2022-12-18 20:24 UTC, FRidere commented on Pochuev/contest2/contest22.cpp
> +        int n;
да, простите, просто в какой-то момент перешел на линукс и писал в блокнотике, так что не усмотрел за форматированием

2022-12-27 16:01 UTC, FRidere reviewed
перерешал задачи последнего контеста, постарался почистить код во всех файлах

2022-12-27 16:55 UTC, FRidere commented on Pochuev/contest1/Source.cpp
> +//		for (auto& ch : str)
почистил

2023-01-07 19:56 UTC, frogitcher approved these changes

2023-01-07 19:56 UTC, merged